### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by ghost** [darkquasar/WMI_Persistence#1]
C:\Python27\study
> python WMIPers.py C:\Windows\System32\wbem\Repository\OBJECTS.DATA
  File "WMIPers.py", line 47
    FilterToConsumerBindings = re.compile(rb'\x80\x00__FilterToConsumerBinding\x00.*?(?:\:|)(\w*?EventConsumer)\.Name\=\"([\w\s]*)\".*?EventFilter\.Name\=\"([\w\s]*)\"')

       ^
SyntaxError: invalid syntax

Any idea on how to resolve this problem?

**Comment by darkquasar** [comment]
Hi calcspring, unfortunately the script only works with Python 3.0+, apologies! (in a future improvement I will compile it with cython so that it can run as an EXE not requiring any python interpreters)
